### ISSUE TITLE
if esme closed by gui/cli, the counter is not reset

### ISSUE THREAD

**Issue by nhanth87** [RestComm/smpp-extensions#10]
the internal counter for enquireLink is not reset if connection closed from gui/cli side
this.rxEnquireLinkCounter

**Comment by nhanth87** [comment]
we can test this by using 2 SMSC servers
   - close 1 esme immediately, check counter in GUI is reset
   - start that esme again and check other smsc keep dropping connection.

**Comment by vetss** [comment]
Fixed by:
https://github.com/RestComm/smpp-extensions/commit/9fea762b581b8219d8a94942c3428c4258ad2eba
