### ISSUE TITLE
linkDropServer need to be considered deliver_sm responded for RECEIVER bind type

### ISSUE THREAD

**Issue by nhanth87** [RestComm/smpp-extensions#12]
If bind type is RECEIVER, the esme will not send any dataSM and just responded for deliver_sm. we need to count it for linkDropServer

**Comment by vetss** [comment]
Fixed for several parameters by:
https://github.com/RestComm/smpp-extensions/commit/8b375fd17515c4c88cdd34aa4762376c825f56df
