### ISSUE TITLE
ESME Client type connection does not reconnect after network connection failure

### ISSUE THREAD

**Issue by vetss** [RestComm/smpp-extensions#24]
Sometimes (not after every TCP connection break) Client ESME may not tries to reconnect.

- This ESME looks connected in GUI interface
- TCP connection may be up and we can see SMPP messages like deliver_sm from a peer. But no outgoing SMPP messages from our side (requests / responses)
- ESME stop / start does not help
- SMSC GW restart helps

This issue is difficult to reproduce locally.

Tickets that are for the topic:
https://telestax.zendesk.com/agent/tickets/34388
https://telestax.zendesk.com/agent/tickets/34491

The reason may be a thread deadlock with intercomminicating with OS level lib or some mulfunction in clud-hopper SMPP stack or some other issue.

**Comment by olenara** [comment]
Also related 87b4614c59500589427aa6f7b84fda2a161b3e23
