### ISSUE TITLE
ESME congestion control

### ISSUE THREAD

**Issue by vetss** [RestComm/smpp-extensions#31]
We need to introduce a congestion control per ESME when a sending queue increased some threshold.

ESME creation / update extra commands :
overload-threshold xxx - a threshold after which ESME is treated as congested (messages will not be sent to it)
normal-threshold yyy - a threshold after which ESME is treated as uncongested (messages will not be sent again to it)
must be: xxx > yyy

**Comment by vetss** [comment]
What is missed for now:
- GUI allows only change values, current values are not displayed.
- Let's make GUI show also a congested state of each ESME
- CLI ESME show does not display a congested state too (only threasholds), let's add it into CLI too
- no update in manul with a new functionality description
- no update for a CLI helpers

**Comment by vetss** [comment]
What I can suggest in addition of what is already implemented:

1) we need also a sever level congestion option. If ESME thesholds are not configured then a server will reuse of server level settings for such ESMEs. This can help customers for default settings when SMPP network similar.

2) 2 levels of congestion (two threasholds then). 
- Level "no congestion"==0
- level "low congestion"==1, we do not restrict traffic for it, it works as a warning
- level "hight congestion"==2, we stop of sending of traffic to a ESME

**Comment by olenara** [comment]
SMSC Admin Guide should also be updated
